
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 01 02:02:38 GMT-04:00 2021
//----------------------------------------------------

package clases;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 12;
  public static final int Class = 9;
  public static final int Coma = 33;
  public static final int Double = 17;
  public static final int Llave_c = 31;
  public static final int Op_booleano = 11;
  public static final int Literal = 19;
  public static final int Llave_a = 30;
  public static final int If = 20;
  public static final int Else = 21;
  public static final int Long = 15;
  public static final int While = 22;
  public static final int Division = 27;
  public static final int Int = 3;
  public static final int Float = 16;
  public static final int Parentesis_c = 29;
  public static final int Parentesis_a = 28;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int PuntoyComa = 34;
  public static final int Linea = 2;
  public static final int Private = 8;
  public static final int Char = 4;
  public static final int ERROR = 37;
  public static final int Do = 6;
  public static final int Op_logico = 13;
  public static final int Public = 7;
  public static final int Short = 14;
  public static final int String = 5;
  public static final int Identificador = 35;
  public static final int Resta = 25;
  public static final int Caracter = 10;
  public static final int Bool = 18;
  public static final int Multiplicacion = 26;
  public static final int Numero = 36;
  public static final int Suma = 24;
  public static final int Main = 32;
  public static final int Igual = 23;
}

