
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 01 19:55:44 GMT-04:00 2021
//----------------------------------------------------

package clases;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 13;
  public static final int Class = 10;
  public static final int Coma = 34;
  public static final int Double = 18;
  public static final int Llave_c = 32;
  public static final int Op_booleano = 12;
  public static final int Literal = 20;
  public static final int Llave_a = 31;
  public static final int If = 21;
  public static final int Else = 22;
  public static final int Long = 16;
  public static final int Return = 2;
  public static final int While = 23;
  public static final int Division = 28;
  public static final int Int = 4;
  public static final int Float = 17;
  public static final int Parentesis_c = 30;
  public static final int Parentesis_a = 29;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int PuntoyComa = 35;
  public static final int Linea = 3;
  public static final int Private = 9;
  public static final int Char = 5;
  public static final int ERROR = 38;
  public static final int Do = 7;
  public static final int Op_logico = 14;
  public static final int Public = 8;
  public static final int Short = 15;
  public static final int String = 6;
  public static final int Identificador = 36;
  public static final int Resta = 26;
  public static final int Caracter = 11;
  public static final int Bool = 19;
  public static final int Multiplicacion = 27;
  public static final int Numero = 37;
  public static final int Suma = 25;
  public static final int Main = 33;
  public static final int Igual = 24;
}

